package org.epragati.constants;

public enum Schedulers {
	BIDCLOSING,
	NUMBERPOOL,
	SPPAYMENTVERIFY,
	FINALPAYMENTVERIFY,
	CFSTSYNC,
	APPLICATIONLOCKINGMECHANISMS,
	CFSTTO,
	TREXPIRED,
	PRREOPEN,
	HSRPTRANDPRPOST,
	CFSTTAXSCHEDULER,
	REGSERUNLOCK,OSNOCAUTOAPPROVALS,
	VAHANSYNCRESPONSE,
	VAHANSYNC,
	NEWREGAUTOVERIFYPAY,
	REGSERVICESAUTOVERIFYPAY,
	TOKENAUTHENTICATION,
	FRESHRC,
	NONPAYMENTREPORT,
	STOPPAGE,
	PRNUMBERGENERATION,
	REGISTRATIONCOUNT,
	VAHANSYNCNOC,
	REGSERAUTOACTION,
	NEWREGAUTOACTION,
	//For SAS Data
	SAS_FLOWDETAILS,
	SAS_PAYMENTS,
	SAS_PERMITDETAILS,
	SAS_TAXDETAILS,
	SAS_REGISTRATIONDETAILS,
	CALUCLATEREGISTRATIONCOUNT,
	AUTO_APPROVAL, HSRPTRPOST, HSRPPRPOST
		;
}
